/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.ContaBanco;
import model.DonoConta;
import controller.ContaController;

import javax.swing.*;

/**
 *
 * @author ps434
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    private ContaBanco contaAtual;
    private ContaController controller = new ContaController();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        popupMenu2 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        lbDadosConta = new javax.swing.JLabel();
        btnOperacao = new javax.swing.JButton();
        areaLog = new java.awt.TextArea();
        btnNovo = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta Bancária");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conta Bancária");

        lbDadosConta.setText("Dados da Conta");

        btnOperacao.setText("Operação");
        btnOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoActionPerformed(evt);
            }
        });

        areaLog.setEditable(false);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(lbDadosConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOperacao))
                    .addComponent(areaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbDadosConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperacao)
                    .addComponent(btnNovo))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoActionPerformed
        // TODO add your handling code here:
        abrirDepositoOuSaque();
    }//GEN-LAST:event_btnOperacaoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        DialogCriarConta dialog = new DialogCriarConta(this, this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    //Método de Exibição
    public void exibirConta() {
        if (contaAtual != null) {
            DonoConta dono = contaAtual.getDono();
            areaLog.setText("");
            areaLog.append("=== Dados da Conta ===\n");
            areaLog.append("Número da Conta: " + contaAtual.getNumConta() + "\n");
            areaLog.append("Titular: " + dono.getNome() + "\n");
            areaLog.append("Tipo: " + contaAtual.getTipo().toUpperCase() + "\n");
            areaLog.append("CPF: " + dono.getCpf() + "\n");

            if (dono.getEmail() != null) {
                areaLog.append("Email: " + dono.getEmail() + "\n");
            }
            if (dono.getTelefone() != null) {
                areaLog.append("Telefone: " + dono.getTelefone() + "\n");
            }
            if (dono.getEndereço() != null) {
                areaLog.append("Endereço: " + dono.getEndereço() + "\n");
            }

            areaLog.append("-----------------------------\n");
            areaLog.append(String.format("Saldo Atual: R$ %.2f\n", contaAtual.getSaldo()));
        } else {
            areaLog.setText("Nenhuma conta cadastrada no momento.\n");
        }
    }

    //Seleção de Depósito ou Saque
    public void abrirDepositoOuSaque() {
        if (contaAtual == null) {
            JOptionPane.showMessageDialog(this,
                    "Nenhuma conta ativa. Cadastre uma conta primeiro!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        JTextField valorField = new JTextField();

        String[] opcoes = {"Depósito", "Saque"};
        JComboBox<String> comboOperacao = new JComboBox<>(opcoes);

        Object[] mensagem = {
            "Valor:", valorField,
            "Operação:", comboOperacao
        };

        int option = JOptionPane.showConfirmDialog(
                this,
                mensagem,
                "Depósito / Saque",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (option == JOptionPane.OK_OPTION) {
            try {
                float valor = Float.parseFloat(valorField.getText());
                String operacao = (String) comboOperacao.getSelectedItem();

                if (valor <= 0) {
                    throw new IllegalArgumentException("O valor deve ser maior que zero.");
                }

                if (operacao.equals("Depósito")) {
                    contaAtual.depositar(valor);
                    JOptionPane.showMessageDialog(this,
                            String.format("Depósito de R$ %.2f realizado com sucesso!", valor),
                            "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    contaAtual.sacar(valor);
                    JOptionPane.showMessageDialog(this,
                            String.format("Saque de R$ %.2f realizado com sucesso!", valor),
                            "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE);
                }

                exibirConta();

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Insira um valor numérico válido.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this,
                        e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void setContaAtual(ContaBanco conta) {
        this.contaAtual = conta;
    }

    public ContaBanco getContaAtual() {
        return this.contaAtual;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea areaLog;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOperacao;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDadosConta;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables

}
